# Generated by Django 5.2.5 on 2026-01-28 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_director_movie_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
