# Generated by Django 5.2.5 on 2026-01-30 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_movie_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='trailer_url',
            field=models.URLField(blank=True, help_text='Youtube Link (e.g., https://www.youtube.com/watch?v=...)', null=True),
        ),
    ]
