# Generated by Django 5.2.5 on 2026-02-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_movie_trailer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_score',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
