# Generated by Django 5.2.5 on 2026-02-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_movie_imdb_score'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(blank=True, help_text='Paste the IMDb ID (e.g., tt7286456) to get live scores automatically.', max_length=20, null=True),
        ),
    ]
